import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import App from "../components/App";

import { QueryClient, QueryClientProvider } from "react-query";

export default function Home() {
  const queryClient = new QueryClient();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <QueryClientProvider client={queryClient}>
        <section>
          <App />
        </section>
      </QueryClientProvider>
    </div>
  );
}
